// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yfjbpfftntrydyqyxjtr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlmamJwZmZ0bnRyeWR5cXl4anRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NjE4MzcsImV4cCI6MjA2OTAzNzgzN30.ewrE8jWHn1Z-ggOclDT0sfPTXAryirXTpPpg7RJWVtM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});